# This is a basic workflow to help you get started with Actions

name: testCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_id:
    name: job_name
    runs-on: ubuntu-latest
    env:
      KEY_1: 123
      KEY_2: 321
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: step_first
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: step_2
      run: echo $job_id.env.key1

    # Runs a set of commands using the runners shell
    - name: step_3
      run: |
        echo $job_id.env.KEY_1,
        echo $job_id.env.KEY_2.
