# This is a basic workflow to help you get started with Actions

name: testCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_001:
    name: test_job
    runs-on: ubuntu-latest
    env:
      KEY_1: 123
      KEY_2: 321
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: step_first
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: use_shell
      id: strep_2_id
      env:
        KEY_1: 8976554
        KEY_3: chengqun
      run: |
       pwd
       whoami
       echo "$PWD"
       echo $KEY_1
       echo ${KEY_1}
       echo "${KEY_3:0:4}"
       echo ${KEY_3:0:4}
       echo ${{github.event_name}}
       echo ${{github}}
       

    # Runs a set of commands using the runners shell
    - name: ssh_login
      continue-on-error: true
      run: |
        ssh -p 31415 dev@120.24.179.212 
    - name: another_ssh_login
      if: ${{ failure() }}
      run: |
        echo "${?}"
        
    - name: docker_operation
      run: |
        docker ps 
